### ISSUE TITLE
Is there a way to get the last part of the crumb

### ISSUE THREAD

**Issue by AirTechWick** [cunneen/vscode-copy-breadcrumbs#1]
![image](https://github.com/cunneen/vscode-copy-breadcrumbs/assets/82003999/4976ea50-246a-4bfc-abc1-04bb95937d1e)

**Comment by AirTechWick** [comment]
Getting the last part of the crumb only would be helpful for me

**Comment by cunneen** [comment]
Hi @AirTechWick ! Great idea!
