### ISSUE TITLE
Optional backticks or other pre-post character

### ISSUE THREAD

**Issue by elfnor** [cunneen/vscode-copy-breadcrumbs#3]
Could you add an option to pre and post fix a character to the breadcrumbs
Default ` back tick  for pasting into markdown as inline code.

Thanks

**Comment by cunneen** [comment]
Hi @elfnor , if you just type a single backtick before pasting, it should paste your breadcrumbs between the back-ticks. Does that do what you need?

**Comment by elfnor** [comment]
Yep that works in most editors set up for markdown, vscode, obsidian, but not in a plain text editor. Its not a big thing to type both backticks, just to remember...
